// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQ7p8kMZAt8dHIMCZ54PyaOG9CPbGnws',
    appId: '1:882968677384:web:4d64a85a3ad3061e8a15bd',
    messagingSenderId: '882968677384',
    projectId: 'mero-tv-1',
    authDomain: 'mero-tv-1.firebaseapp.com',
    storageBucket: 'mero-tv-1.firebasestorage.app',
    measurementId: 'G-3CRP9JD6HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlR8pEMqaRImqP71qa6f3n6H9h6fBPjNw',
    appId: '1:882968677384:android:9aa9e89e716805008a15bd',
    messagingSenderId: '882968677384',
    projectId: 'mero-tv-1',
    storageBucket: 'mero-tv-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWhqkpwiCoKAzQ1OYaAFpOIoQo2j4iSI',
    appId: '1:882968677384:ios:a6f44a95ee22b52c8a15bd',
    messagingSenderId: '882968677384',
    projectId: 'mero-tv-1',
    storageBucket: 'mero-tv-1.firebasestorage.app',
    iosBundleId: 'com.example.meroTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWhqkpwiCoKAzQ1OYaAFpOIoQo2j4iSI',
    appId: '1:882968677384:ios:a6f44a95ee22b52c8a15bd',
    messagingSenderId: '882968677384',
    projectId: 'mero-tv-1',
    storageBucket: 'mero-tv-1.firebasestorage.app',
    iosBundleId: 'com.example.meroTv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZQ7p8kMZAt8dHIMCZ54PyaOG9CPbGnws',
    appId: '1:882968677384:web:9913b052c0b4f3168a15bd',
    messagingSenderId: '882968677384',
    projectId: 'mero-tv-1',
    authDomain: 'mero-tv-1.firebaseapp.com',
    storageBucket: 'mero-tv-1.firebasestorage.app',
    measurementId: 'G-17F6PBZCDL',
  );
}
